services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/student_scheduler
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: python run.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=student_scheduler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: