apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-scheduler
  labels:
    app: student-scheduler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-scheduler
  template:
    metadata:
      labels:
        app: student-scheduler
    spec:
      containers:
      - name: student-scheduler
        image: your-registry/student-scheduler:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-scheduler-service
spec:
  selector:
    app: student-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
