apiVersion: v2
name: student-scheduler
description: A Helm chart for Student Scheduler application
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
